name: mattiunliker
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flashy_tab_bar2: ^0.0.10
  sliding_clipped_nav_bar: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/mattiunliker.png"

flutter:
  uses-material-design: true
  assets:
    - images/frist.png
    - images/Social -uihut.png
    - images/Group 370.png
    - images/Ellipse 307.png
    # ... (rest of your image list)
